export const SITE_URL='https://ascore.ae'
export const servicePages=[
 {id:'digital-experiences',name:'Digital experiences',path:'/services/digital-experiences/',title:'Web, App & Ecommerce Development UAE | Ascore Creative',description:'Plan and build responsive websites, apps, ecommerce and product interfaces with Ascore Creative, an Ajman-based studio serving the UAE and beyond.',lead:'Digital products with a clearer path from first visit to next action.',intro:'We bring structure, design and engineering together for websites and products that are useful, coherent and easy to navigate.',deliverables:['Responsive websites and landing pages','Web and app interface design','Ecommerce experiences and storefronts','Prototypes, component systems and handover'],process:[['Understand the experience','Map the audience, content, key actions and technical requirements.'],['Shape the interface','Develop the information architecture, wireframes and visual direction.'],['Build and refine','Implement the agreed scope, review responsive behavior and prepare the handover.']]},
 {id:'brand-creative',name:'Brand & creative',path:'/services/brand-creative/',title:'Branding & Creative Services UAE | Ascore Creative',description:'Identity, art direction, campaigns and motion systems from Ascore Creative. Brand and creative services for UAE businesses and global projects.',lead:'A distinct identity. A consistent way to show up.',intro:'We shape the visual language that connects a brand across its identity, digital touchpoints and creative campaigns.',deliverables:['Brand direction and visual identity','Art direction and design systems','Campaign and channel-ready creative','Motion assets and practical brand guidelines'],process:[['Find the direction','Clarify the audience, positioning and visual ambition.'],['Develop the system','Explore concepts and refine the identity around an agreed direction.'],['Apply it consistently','Prepare the selected assets and guidance for the channels in scope.']]},
 {id:'3d-immersive',name:'3D & immersive',path:'/services/3d-immersive/',title:'3D & Immersive Experiences UAE | Ascore Creative',description:'Spatial design, interactive 3D and real-time web experiences from Ascore Creative. Explore immersive creative services for UAE and global brands.',lead:'Give an idea space, depth and movement.',intro:'We combine spatial design and interactive storytelling to create digital experiences that invite people to look closer.',deliverables:['3D concepts and visual assets','Interactive web scenes and hero experiences','Motion studies and animation exports','Responsive integration and performance refinement'],process:[['Define the story','Choose what the experience should communicate and how people will interact.'],['Build the visual world','Develop the form, material, lighting and motion direction.'],['Make it usable','Integrate the assets, test the agreed devices and provide a static motion fallback.']]},
 {id:'growth-automation',name:'Growth & automation',path:'/services/growth-automation/',title:'Growth & AI Automation UAE | Ascore Creative',description:'Performance marketing, AI-assisted workflows and connected digital operations from Ascore Creative. Growth and automation support for UAE businesses.',lead:'Connect the creative work to the way your business operates.',intro:'We help define the campaigns, workflows and connections that support a more coordinated digital operation.',deliverables:['Performance marketing planning','Campaign creative and iteration support','AI-assisted workflow design','CRM and operational integration support'],process:[['Map the current flow','Understand the channels, handoffs, tools and available measurement.'],['Choose useful changes','Define the campaign or workflow scope and required access.'],['Connect and review','Implement the approved work and review it against the agreed operational goals.']]},
 {id:'uae-business-services',name:'UAE business services',path:'/services/uae-business-services/',title:'UAE Tax, VAT & Business Support | Ascore Creative',description:'Corporate tax, VAT and business support from Ascore Creative. Discuss record preparation, engagement scope and compliance coordination for your UAE business.',lead:'More clarity around the practical work of running a business.',intro:'Alongside creative and digital work, we offer UAE business support across corporate tax, VAT and compliance coordination. The engagement scope and any specialist involvement are agreed before work begins.',deliverables:['Corporate tax and VAT support within an agreed scope','Business record preparation and organisation','Compliance coordination and next-step planning','Digital workflows for business operations'],process:[['Clarify the request','Identify the business support needed and agree who is responsible for each part.'],['Prepare the information','Organise the relevant records and confirm the engagement requirements.'],['Coordinate the next steps','Support the agreed workflow and hand over the records and outstanding actions.']]},
]
export const publicRoutes=[
 {id:'home',path:'/',label:'Home',title:'Ascore Creative | Creative & Digital Agency in the UAE',description:'Ascore Creative is an Ajman-based creative and digital agency serving Dubai, the UAE and global projects through brand, web, app, 3D and automation services.'},
 {id:'work',path:'/work/',label:'Work',title:'Selected Work & Digital Studies | Ascore Creative',description:'Explore selected websites presented by Ascore Creative. Artwork is illustrative and clearly labeled; project links open the existing websites.'},
 {id:'services',path:'/services/',label:'Services',title:'Creative & Digital Agency Services UAE | Ascore Creative',description:'Explore branding, web and app development, ecommerce, immersive 3D, growth, AI automation and UAE business support from Ascore Creative.'},
 ...servicePages.map(service=>({...service,label:service.name,service:true})),
 {id:'about',path:'/about/',label:'About',title:'About Ascore Creative | Ajman-Based UAE Creative Agency',description:'Ascore Creative brings strategy, design and engineering together. Meet the approach of an Ajman-based studio serving Dubai, the UAE and global projects.'},
 {id:'contact',path:'/contact/',label:'Contact',title:'Contact Ascore Creative | Start a UAE or Global Project',description:'Discuss your next brand, website, app or immersive experience with Ascore Creative, an Ajman-based UAE studio. Contact us by email, phone or WhatsApp.'},
]
export const privateRoutes=['/portal/','/portal/login/','/portal/register/','/portal/setup/']
export const normalizePath=pathname=>pathname==='/'?'/':`/${pathname.split('/').filter(Boolean).join('/')}/`
export const routeForPath=pathname=>publicRoutes.find(page=>page.path===normalizePath(pathname))
export const isPrivatePath=pathname=>normalizePath(pathname).startsWith('/portal/')
export function metadataForPath(pathname){
 if(isPrivatePath(pathname))return {title:'Client & Agency Portal | Ascore Creative',description:'Private client and agency workspace. Sign in to access your authorized projects and records.',robots:'noindex,nofollow',canonical:null}
 const route=routeForPath(pathname)
 return route?{...route,robots:'index,follow',canonical:SITE_URL+route.path}:{title:'Page Not Found | Ascore Creative',description:'Find Ascore Creative’s home, services, selected work, studio and contact pages.',robots:'noindex,nofollow',canonical:null}
}
