import {useEffect,useState} from 'react'
import {ArrowUpRight,BookOpen,FolderOpen,Users,BarChart3,CheckCircle2,Clock3} from 'lucide-react'
import TrafficAnalytics from './TrafficAnalytics'
import {portalRequest} from '../../services/portalApi'

const money=(amount,currency='AED')=>new Intl.NumberFormat('en-AE',{style:'currency',currency}).format(amount)
const titles={meta:'Meta Ads',ai:'Practical AI'}

export default function AdminOverview({data,groups,user,onNavigate,refreshKey,analytics=false}){
 const [courses,setCourses]=useState(null),[courseError,setCourseError]=useState('')
 useEffect(()=>{let active=true;portalRequest('/courses/admin/orders').then(value=>{if(active){setCourses(value);setCourseError('')}}).catch(error=>{if(active){setCourses(null);setCourseError(error.message)}});return()=>{active=false}},[refreshKey])
 const privateReady=!!courses&&['schemaReady','privatePdfsReady','senderConfigured'].every(key=>courses.requirements[key])
 const openProjects=data.projects.filter(p=>p.status!=='completed'),activeLeads=data.leads.filter(l=>!['won','lost'].includes(l.status)),summary=courses?.summary
 const statusCounts=['active','in_review','on_hold','completed'].map(id=>({label:id.replaceAll('_',' '),count:data.projects.filter(p=>p.status===id).length}))
 const documentCounts=['quotation','invoice','bill'].map(id=>({label:id+'s',count:data.documents.filter(d=>d.kind===id).length}))
 const metrics=[{label:'Open projects',value:openProjects.length,note:'Includes projects on hold',icon:FolderOpen,target:'projects'},{label:'Registered clients',value:data.clients.length,note:'Client portal accounts',icon:Users,target:'clients'},{label:'Active leads',value:activeLeads.length,note:'Excludes won and lost',icon:BarChart3,target:'leads'},{label:'Test orders · AED 0',value:summary?summary.freeOrders:'—',note:summary?'Saved test orders':courses?'Course database needs setup':'Course data unavailable',icon:BookOpen,target:'courses'}]
 return <div className="admin-overview">
  {!analytics&&<section className="admin-welcome"><div><p className="admin-eyebrow">YOUR STUDIO, AT A GLANCE</p><h2>Welcome back, {user.name}.</h2><p>Keep an eye on projects, client records and course delivery.</p></div><button type="button" className="admin-primary" onClick={()=>onNavigate('courses')}>View course orders<ArrowUpRight size={16}/></button></section>}
  <TrafficAnalytics refreshKey={refreshKey}/>
  <div className="admin-snapshot"><span><Clock3 size={14}/>Workspace snapshot · All saved records</span><span>Financial tracking in recorded currencies</span></div>
  <div className="admin-metrics">{metrics.map(({label,value,note,icon:Icon,target})=><button type="button" key={label} onClick={()=>onNavigate(target)} className="admin-metric"><div><span>{label}</span><Icon size={17}/></div><strong>{value}</strong><small>{note}</small></button>)}</div>
  <div className="admin-overview-grid">
   <section className="admin-card admin-finance"><div className="admin-card-heading"><div><h3>Invoice balances</h3><p>Recorded settlements; no online payment is collected here.</p></div><button type="button" onClick={()=>onNavigate('documents')}>View finance<ArrowUpRight size={14}/></button></div>{Object.keys(groups).length?<div className="admin-currency-groups">{Object.entries(groups).map(([currency,total])=><div key={currency}><span className="admin-currency">{currency}</span><dl><div><dt>Invoiced</dt><dd>{money(total.amount,currency)}</dd></div><div><dt>Recorded paid</dt><dd>{money(total.paid,currency)}</dd></div><div><dt>Outstanding</dt><dd>{money(total.balance,currency)}</dd></div></dl></div>)}</div>:<div className="admin-empty"><FolderOpen size={24}/><h4>No invoices recorded yet</h4><p>Balances will appear when an invoice is saved. Quotations and bills are excluded from these totals.</p><button type="button" onClick={()=>onNavigate('documents')}>Open finance</button></div>}</section>
   <section className="admin-card admin-course-readiness"><div className="admin-card-heading"><div><h3>Course delivery</h3><p>Readiness from the private course service.</p></div><BookOpen size={18}/></div>{courses?<><p className={'admin-state '+(privateReady?'ready':'pending')}>{privateReady?<CheckCircle2 size={15}/>:<Clock3 size={15}/>} {privateReady?'Private prerequisites verified':'Setup needed before private testing'}</p><ul>{[['schemaReady','Course database'],['privatePdfsReady','Approved private PDFs'],['senderConfigured','Sender configured'],['enabled','Public zero-payment checkout']].map(([key,label])=><li key={key}><span>{label}</span><strong className={(key==='enabled'?!courses.requirements[key]:courses.requirements[key])?'ready':'pending'}>{key==='enabled'?(courses.requirements[key]?'Enabled':'Disabled'):(courses.requirements[key]?'Ready':'Pending')}</strong></li>)}</ul><p className="admin-footnote">Sender configuration is not proof of email delivery. Keep public zero-payment checkout and paid checkout disabled.</p></>:<div className="admin-empty"><p>{courseError||'Loading private readiness…'}</p></div>}<button type="button" onClick={()=>onNavigate('courses')}>Open delivery setup<ArrowUpRight size={14}/></button></section>
  </div>
  {analytics?<div className="admin-overview-grid"><CountChart title="Projects by status" counts={statusCounts} total={data.projects.length}/><CountChart title="Financial document types" counts={documentCounts} total={data.documents.length}/><section className="admin-card"><div className="admin-card-heading"><div><h3>Zero-payment test orders over time</h3><p>Last seven days · UTC · Persisted orders</p></div></div>{courses?.daily?.length?<div className="admin-count-chart">{courses.daily.map(day=><div key={day.date}><span>{day.date}</span><div className="admin-chart-track"><span style={{width:`${day.freeOrders/Math.max(1,...courses.daily.map(d=>d.freeOrders))*100}%`}}/></div><strong>{day.freeOrders}</strong></div>)}</div>:<div className="admin-empty"><p>{summary?'No test orders recorded in the last seven days.':'Order analytics await course database setup.'}</p></div>}</section></div>:<section className="admin-card"><div className="admin-card-heading"><div><h3>Current projects</h3><p>Latest saved project records</p></div><button type="button" onClick={()=>onNavigate('projects')}>View all<ArrowUpRight size={14}/></button></div>{openProjects.length?<div className="admin-project-list">{openProjects.slice(0,5).map(p=><button type="button" key={p.id} onClick={()=>onNavigate('projects',p.id)}><div><strong>{p.title}</strong><small>{p.currentStage} · {p.status.replaceAll('_',' ')}</small></div><span>{p.progressPercentage}%<ArrowUpRight size={14}/></span></button>)}</div>:<div className="admin-empty"><FolderOpen size={24}/><h4>No open projects</h4><p>Create a project after a client account is registered.</p><button type="button" onClick={()=>onNavigate('projects')}>Open projects</button></div>}</section>}
  {analytics&&<p className="admin-footnote">Charts use saved workspace records. Invoice totals are grouped by currency and do not include course test orders.</p>}
  {!analytics&&<div className="admin-shortcuts">{[['courses','Course orders','Check delivery, private PDFs and test orders.',BookOpen],['documents','Finance','Review quotations, invoices and recorded settlements.',FolderOpen],['analytics','Analytics','Explore counts and balances from saved records.',BarChart3]].map(([target,title,copy,Icon])=><button type="button" key={target} onClick={()=>onNavigate(target)}><Icon size={21}/><strong>{title}</strong><span>{copy}</span><ArrowUpRight size={16}/></button>)}</div>}
  {!analytics&&courses?.assets?.length>0&&<p className="admin-footnote">Private PDFs: {courses.assets.map(a=>`${titles[a.id]||a.name} ${a.installed?'verified':'pending'}`).join(' · ')}.</p>}
 </div>
}

function CountChart({title,counts,total}){return <section className="admin-card"><div className="admin-card-heading"><div><h3>{title}</h3><p>{total} saved {total===1?'record':'records'}</p></div></div>{total?<div className="admin-count-chart">{counts.map(({label,count})=><div key={label}><span>{label}</span><div className="admin-chart-track"><span style={{width:`${count/Math.max(1,total)*100}%`}}/></div><strong>{count}</strong></div>)}</div>:<div className="admin-empty"><p>No records yet. A chart will appear when data is available.</p></div>}</section>}
