import {useState} from 'react'
const colors=['#27674e','#80a275','#d5b362','#6975a2','#b58581','#92b8b1','#c4c8a6','#a992ba','#6c8da3','#b0a39a']
const count=n=>n.toLocaleString('en-AE')
export function DonutChart({title,rows,note}){
 const values=rows.filter(r=>r.sessions>0),total=values.reduce((n,r)=>n+r.sessions,0);let accumulated=0
 return <section className="analytics-chart-card"><h4>{title}</h4><p>{note}</p>{total?<div className="analytics-donut-layout"><svg className="analytics-donut" viewBox="0 0 180 180" role="img" aria-label={`${title}: ${total} sessions in displayed rows`}><circle cx="90" cy="90" r="65" fill="none" stroke="#edf1ed" strokeWidth="24"/>{values.map((row,i)=>{const offset=accumulated;accumulated+=row.sessions/total*100;return <circle key={i} cx="90" cy="90" r="65" fill="none" stroke={colors[i%colors.length]} strokeWidth="24" pathLength="100" strokeDasharray={`${row.sessions/total*100} 100`} strokeDashoffset={-offset} transform="rotate(-90 90 90)"><title>{row.label}: {row.sessions} sessions ({(row.sessions/total*100).toFixed(1)}%)</title></circle>})}<text x="90" y="89" textAnchor="middle" className="donut-total">{count(total)}</text><text x="90" y="108" textAnchor="middle" className="donut-caption">sessions</text></svg><ul className="analytics-legend">{values.map((row,i)=><li key={i}><span><i style={{background:colors[i%colors.length]}}/>{row.label}</span><strong>{count(row.sessions)}<small>{(row.sessions/total*100).toFixed(1)}%</small></strong></li>)}</ul></div>:<p className="admin-empty">No sessions reported for this period.</p>}</section>
}
export default function AnalyticsCharts({history}){
 const [metric,setMetric]=useState('sessions'),rows=history.daily||[],max=Math.max(1,...rows.map(r=>r[metric])),x=i=>rows.length===1?320:48+i/(rows.length-1)*552,y=n=>178-n/max*140
 return <div className="analytics-charts"><section className="analytics-chart-card analytics-trend"><div className="admin-card-heading"><div><h4>Traffic over time</h4><p>Recorded dates · {history.timeZone} · {metric==='activeUsers'?'Active users':metric==='pageViews'?'Page views':'Sessions'}</p></div><label className="commerce-field">Chart metric<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="sessions">Sessions</option><option value="activeUsers">Active users</option><option value="pageViews">Page views</option></select></label></div>{rows.length?<><svg viewBox="0 0 640 220" role="img" aria-label={`${metric} over ${rows.length} reported days`} className="analytics-line">{[0,.5,1].map(t=><g key={t}><line x1="48" x2="600" y1={y(t*max)} y2={y(t*max)} stroke="#e0e7e1"/><text x="37" y={y(t*max)+4} textAnchor="end">{Math.round(t*max)}</text></g>)}{rows.length===1&&<g><rect x="286" y={y(rows[0][metric])} width="68" height={178-y(rows[0][metric])} rx="6" fill="#80a275"/><text x="320" y={Math.max(22,y(rows[0][metric])-12)} textAnchor="middle">{count(rows[0][metric])}</text></g>}{rows.length>1&&<polyline fill="none" stroke="#27674e" strokeWidth="3" points={rows.map((r,i)=>`${x(i)},${y(r[metric])}`).join(' ')}/>} {rows.map((r,i)=><circle key={r.date} cx={x(i)} cy={y(r[metric])} r="4" fill="#27674e"><title>{r.date}: {r[metric]} {metric}</title></circle>)}<text x="48" y="207">{rows[0].date}</text><text x="600" y="207" textAnchor="end">{rows.at(-1).date}</text></svg>{rows.length===1&&<p className="admin-footnote">One date has reported traffic: {rows[0].date}. The bar shows {count(rows[0][metric])} {metric==='activeUsers'?'active users':metric==='pageViews'?'page views':'sessions'}. A trend appears as more dates are recorded.</p>}<details className="analytics-data"><summary>View daily values</summary><div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Date</th><th>Sessions</th><th>Active users</th><th>Page views</th></tr></thead><tbody>{rows.map(r=><tr key={r.date}><td>{r.date}</td><td>{count(r.sessions)}</td><td>{count(r.activeUsers)}</td><td>{count(r.pageViews)}</td></tr>)}</tbody></table></div></details></>:<p className="admin-empty">No processed daily traffic returned for this period yet. Today’s data can lag behind Realtime; try Yesterday or 7 days.</p>}</section><DonutChart title="Traffic sources" rows={history.sources.map(r=>({label:r.source+' / '+r.medium,sessions:r.sessions}))} note="Top 10 sources · share of displayed sessions"/>{history.available&&<><DonutChart title="Devices" rows={history.devices} note="Sessions by device category"/><DonutChart title="Countries" rows={history.countries} note="Top 10 countries · share of displayed sessions"/></>}{history.error&&<p role="status">{history.error}</p>}{history.thresholded||history.otherRow?<p className="admin-footnote">Google privacy thresholds or grouped rows can limit these breakdowns.</p>:null}</div>
}
