import {useCallback,useEffect,useState} from 'react'
import {portalRequest} from '../../services/portalApi'
export default function CourseSessions(){
 const [data,setData]=useState(null),[join,setJoin]=useState(''),[key,setKey]=useState(''),[enabled,setEnabled]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const refresh=useCallback(async()=>{try{const result=await portalRequest('/courses/admin/sessions');setData(result);setJoin(result.joinUrl);setEnabled(result.enabled||!result.schemaReady)}catch(e){setError(e.message)}},[])
 useEffect(()=>{refresh()},[refresh])
 const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{await portalRequest('/courses/admin/sessions',{method:'POST',body:{joinUrl:join,key,enabled}});setKey('');setNotice('Friday email connection saved. Run the Google script’s setup verification and install its cloud schedule to activate sending.');await refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="workspace-panel course-setup friday-session-setup" aria-labelledby="friday-session-heading"><h3 id="friday-session-heading">Friday live sessions</h3><p>Paid Meta Ads customers, including bundle buyers, receive one individual email each Friday at 9 AM UAE for the 2 PM Google Meet. Sender: <strong>ascorecreative@gmail.com</strong>.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{data&&<><p>Connection: <strong>{data.enabled?'Enabled':'Not enabled'}</strong> · Google last checked: <strong>{data.lastCheckAt?new Date(data.lastCheckAt).toLocaleString('en-AE',{timeZone:'Asia/Dubai'}):'Not verified yet'}</strong></p>{data.setupAllowed&&<form onSubmit={save}><label>Friday Google Meet link<input type="url" value={join} onChange={e=>setJoin(e.target.value)} required placeholder="https://meet.google.com/abc-defg-hij"/></label><label>Private Google automation key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required pattern="[a-f0-9]{64}"/></label><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enable Friday emails</label><button type="submit" disabled={busy}>{busy?'Saving…':'Save Friday email connection'}</button></form>}<button type="button" disabled={busy} onClick={refresh}>Refresh Friday status</button>{data.deliveries.length>0&&<table className="workspace-table"><thead><tr><th>Friday</th><th>Email outcome</th><th>Customers</th></tr></thead><tbody>{data.deliveries.map(row=><tr key={row.week+row.state}><td>{row.week}</td><td>{row.state==='accepted'?'Accepted by Google':row.state==='sending'?'Sending / needs review':row.state}</td><td>{row.count}</td></tr>)}</tbody></table>}<p className="admin-footnote">Google acceptance does not guarantee inbox delivery. Uncertain sends are held for review and never automatically repeated. Google’s scheduler can run shortly after 9 AM; an outage can delay sending until before the 2 PM session.</p></>}</section>
}
