import {useCallback,useEffect,useState} from 'react'
import {ArrowLeft} from 'lucide-react'
import {portalRequest} from '../../services/portalApi'
import {TagList,WorkspaceSetup} from './CommerceShared'
import {commerceMoney as money,commerceDate as date,customerName as name,orderNumber,paymentLabel,deliveryLabel,parseTags} from './commerce-format'
export default function CustomersWorkspace({refreshKey,selectedId,onSelect,onOrder}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState('')
 const load=useCallback(async()=>{try{setData(await portalRequest('/courses/admin/customers'));setError('')}catch(e){setError(e.message)}},[])
 useEffect(()=>{load()},[load,refreshKey,selectedId])
 if(selectedId)return <CustomerDetail key={selectedId} id={selectedId} refreshKey={refreshKey} onBack={()=>onSelect(null)} onOrder={onOrder}/>
 const visible=data?.customers.filter(c=>[c.name,c.email,...c.tags].join(' ').toLowerCase().includes(query.trim().toLowerCase()))||[]
 return <section className="customers-workspace"><div className="course-operations-heading"><p>Online customers appear automatically, including guest purchases. Private payment tests are excluded.</p><button type="button" onClick={load}>Refresh customers</button></div>{error&&<p role="alert" className="portal-form-error">{error}</p>}{data&&<WorkspaceSetup ready={data.managementReady} onReady={load} onError={setError}/>}<label className="commerce-field commerce-search">Search customers<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Customer name, email or tag"/></label><div className="commerce-customer-list">{visible.map(c=><button className="commerce-customer-preview" type="button" key={c.id} onClick={()=>onSelect(c.id)}><div><strong>{name(c)}</strong><small>{c.email}</small><TagList tags={c.tags}/></div><div><strong>{c.orders} {c.orders===1?'order':'orders'}</strong><small>{c.paidOrders} paid</small></div><div><strong>{money(c.totalSpentMinor)}</strong><small>Total spent</small></div><small>Latest order<br/>{date(c.lastOrderAt)} UAE</small><span className="order-open">View customer →</span></button>)}</div>{!data&&!error&&<p role="status">Loading customers…</p>}{data&&!visible.length&&<p>No customers match this search.</p>}</section>
}
function CustomerDetail({id,refreshKey,onBack,onOrder}){
 const [data,setData]=useState(null),[orders,setOrders]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[customerName,setName]=useState(''),[tags,setTags]=useState(''),[busy,setBusy]=useState(false)
 const path='/courses/admin/customers/'+id
 const load=useCallback(async()=>{try{const result=await portalRequest(path);setData(result);setName(result.customer.name);setTags(result.customer.tags.join(', '));setOrders(await portalRequest('/courses/admin/order-history?email='+encodeURIComponent(result.customer.email)));setError('')}catch(e){setError(e.message)}},[path])
 useEffect(()=>{load()},[load,refreshKey])
 const save=async e=>{e.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await portalRequest(path,{method:'PATCH',body:{name:customerName,tags:parseTags(tags),revision:data.customer.revision}});setData(result);setName(result.customer.name);setTags(result.customer.tags.join(', '));setNotice('Customer profile saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const c=data?.customer
 return <section className="commerce-detail"><button className="commerce-back" type="button" onClick={onBack}><ArrowLeft size={16}/>All customers</button>{error&&<p role="alert" className="portal-form-error">{error}</p>}{notice&&<p role="status" className="portal-notice">{notice}</p>}{!c&&!error&&<p role="status">Loading customer…</p>}{c&&<><header className="commerce-detail-heading"><div><p className="admin-eyebrow">CUSTOMER PROFILE</p><h2>{name(c)}</h2><p>{c.email}</p></div><TagList tags={c.tags}/></header><WorkspaceSetup ready={data.managementReady} onReady={load} onError={setError}/><div className="commerce-detail-grid"><div className="commerce-detail-main"><div className="commerce-customer-metrics"><div><span>Confirmed spend</span><strong>{money(c.totalSpentMinor)}</strong></div><div><span>Paid orders</span><strong>{c.paidOrders}</strong></div><div><span>Checkout attempts</span><strong>{c.orders}</strong></div></div><section className="admin-card"><h3>Order history</h3><div className="commerce-customer-orders">{orders?.orders.map(o=><button type="button" key={o.source+o.id} onClick={()=>onOrder(o.source+':'+o.id)}><div><strong>{orderNumber(o)}</strong><small>{date(o.createdAt)} UAE</small></div><strong>{money(o.totalMinor)}</strong><div><span>{paymentLabel(o)}</span><small>{deliveryLabel(o)}</small></div><span className="order-open">View order →</span></button>)}</div>{orders?.nextCursor&&<button type="button" onClick={async()=>{try{const next=await portalRequest('/courses/admin/order-history?email='+encodeURIComponent(c.email)+'&cursor='+encodeURIComponent(orders.nextCursor));setOrders({...next,orders:[...orders.orders,...next.orders]})}catch(e){setError(e.message)}}}>Load older orders</button>}</section></div><aside className="commerce-detail-aside"><section className="admin-card"><h3>Customer details</h3><form onSubmit={save}><label className="commerce-field">Full name<input value={customerName} onChange={e=>setName(e.target.value)} required maxLength={100} autoComplete="off"/></label><label className="commerce-field">Customer tags<input value={tags} onChange={e=>setTags(e.target.value)} maxLength={820} placeholder="returning, vip"/></label><p className="admin-footnote">Separate tags with commas. Email: {c.email}</p><button disabled={busy||!data.managementReady}>{busy?'Saving…':'Save customer'}</button></form><dl className="order-detail-facts"><div><dt>First order</dt><dd>{date(c.firstOrderAt)} UAE</dd></div><div><dt>Latest order</dt><dd>{date(c.lastOrderAt)} UAE</dd></div></dl></section></aside></div></>}</section>
}
