import {useCallback,useEffect,useRef,useState} from 'react'
import {X} from 'lucide-react'
import {portalRequest} from '../../services/portalApi'
const names={meta:'Meta Ads',ai:'Practical AI'}
const money=n=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED'}).format(n/100)
const date=n=>new Date(n).toLocaleString('en-AE',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Dubai'})
const number=o=>'AS-'+o.id.slice(0,8).toUpperCase()
const state=o=>o.kind==='zero_payment_test'?'No payment · test':o.paymentStatus==='paid'?'Paid':o.paymentStatus==='review'?'Needs review':o.paymentStatus==='uncertain'?'Uncertain':o.paymentStatus==='pending'?'Unpaid':o.paymentStatus.replaceAll('_',' ')
const delivery=o=>({accepted:'Email accepted',pending:'Pending',sending:'Sending',uncertain:'Needs review',failed:'Email rejected'}[o.delivery]||o.delivery)
export default function OrdersWorkspace({refreshKey,clients=[]}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState(null)
 const opener=useRef(null)
 const buyer=o=>o.customerName||clients.find(c=>c.email.toLowerCase()===o.email.toLowerCase())?.name||o.email||'Private test'
 const load=useCallback(async(cursor=null)=>{setBusy(true);try{const result=await portalRequest('/courses/admin/order-history'+(cursor?'?cursor='+encodeURIComponent(cursor):''));setData(previous=>cursor?{...result,orders:[...(previous?.orders||[]),...result.orders]}:result);setError('')}catch(e){setError(e.message)}finally{setBusy(false)}},[])
 useEffect(()=>{load()},[load,refreshKey])
 const visible=(data?.orders||[]).filter(o=>(filter==='all'||filter==='paid'&&o.paymentStatus==='paid'||filter==='unpaid'&&o.kind==='purchase'&&o.paymentStatus!=='paid'||filter==='tests'&&o.kind!=='purchase')&&(!query.trim()||[number(o),o.id,buyer(o),o.email,...o.items.map(id=>names[id])].join(' ').toLowerCase().includes(query.trim().toLowerCase())))
 return <section className="orders-workspace"><div className="course-operations-heading"><p>Customer purchases, unpaid checkouts and clearly labelled test orders. Private tests and zero-payment orders are excluded from sales totals.</p><button type="button" onClick={()=>load()} disabled={busy}>{busy?'Refreshing…':'Refresh orders'}</button></div>{error&&<p role="alert" className="portal-form-error">{error}</p>}<div className="course-order-controls"><label>Search orders<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Order number, buyer or course"/></label><label>Payment status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All orders</option><option value="paid">Paid</option><option value="unpaid">Unpaid / needs attention</option><option value="tests">Test orders</option></select></label></div><div className="orders-list" aria-label="Order list">{visible.map(o=><button type="button" className="order-preview" key={o.source+o.id} onClick={e=>{opener.current=e.currentTarget;setSelected(o)}}><div><strong>{number(o)}</strong><small>{date(o.createdAt)} UAE</small></div><div><strong>{buyer(o)}</strong>{o.email&&o.customerName&&<small>{o.email}</small>}<small>{o.items.map(id=>names[id]).join(' + ')} · {o.kind==='purchase'?'Customer order':o.kind==='private_test'?'Private payment test':'Zero-payment test'}</small></div><strong>{money(o.totalMinor)}</strong><span className={'order-payment '+(o.paymentStatus==='paid'?'is-paid':'is-pending')}>{state(o)}</span><small>{delivery(o)}</small><span className="order-open">View order →</span></button>)}</div>{!data&&!error&&<p role="status">Loading orders…</p>}{data&&!visible.length&&<p>No orders match this view.</p>}{data?.nextCursor&&<button type="button" disabled={busy} onClick={()=>load(data.nextCursor)}>Load older orders</button>}{selected&&<OrderSummary order={selected} buyer={buyer(selected)} opener={opener} onClose={()=>setSelected(null)}/>}</section>
}
function OrderSummary({order:o,buyer,opener,onClose}){
 const dialog=useRef(null)
 useEffect(()=>{const prior=opener.current,overflow=document.body.style.overflow;document.body.style.overflow='hidden';const key=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const controls=[...dialog.current.querySelectorAll('button,a[href]')];if(!controls.length)return;const i=controls.indexOf(document.activeElement);e.preventDefault();controls[e.shiftKey?(i<=0?controls.length-1:i-1):(i+1)%controls.length].focus()}};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;window.removeEventListener('keydown',key);prior?.focus()}},[opener,onClose])
 return <div className="portal-document-backdrop"><section className="portal-document order-detail" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="order-detail-title"><div className="document-actions"><button type="button" autoFocus onClick={onClose} aria-label="Close order summary"><X size={20}/></button></div><p className="admin-eyebrow">ORDER SUMMARY</p><h2 id="order-detail-title">{number(o)}</h2><p>{buyer}</p><span className={'order-payment '+(o.paymentStatus==='paid'?'is-paid':'is-pending')}>{state(o)}</span><dl className="order-detail-facts"><div><dt>Full order reference</dt><dd>{o.id}</dd></div><div><dt>Client email</dt><dd>{o.email||'No customer · private test'}</dd></div><div><dt>Placed</dt><dd>{date(o.createdAt)} UAE</dd></div><div><dt>Type</dt><dd>{o.kind==='purchase'?'Customer purchase':o.kind==='private_test'?'Private payment test':'Zero-payment test'}</dd></div><div><dt>Email delivery</dt><dd>{delivery(o)}</dd></div><div><dt>Download links expire</dt><dd>{date(o.expiresAt)} UAE</dd></div><div><dt>Included in sales</dt><dd>{o.includedInSales?'Yes':'No'}</dd></div></dl><table><thead><tr><th>Course</th><th>Amount</th></tr></thead><tbody>{o.items.map(id=><tr key={id}><td>{names[id]}</td><td>{money(o.totalMinor/o.items.length)}</td></tr>)}</tbody></table><div className="document-totals"><p>{o.paymentStatus==='paid'?'Total paid':'Order total'}<strong>{money(o.totalMinor)}</strong></p></div>{o.reason&&<p className="portal-form-error">{o.reason}</p>}</section></div>
}
