import {useCallback,useEffect,useState} from 'react'
import {portalRequest} from '../../services/portalApi'
const ranges=[['today','Today'],['yesterday','Yesterday'],['7days','7 days'],['30days','30 days']]
const count=value=>Number.isSafeInteger(value)?value.toLocaleString('en-AE'):'—'
const stamp=value=>value?new Date(value).toLocaleTimeString('en-AE',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—'
export default function TrafficAnalytics({refreshKey}){
 const [range,setRange]=useState('today'),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0)
 const load=useCallback(async(signal)=>{
  setLoading(true)
  try{const next=await portalRequest('/analytics/ga4?range='+range,{signal});if(!signal.aborted){setData(next);setError('')}}catch(e){if(!signal.aborted){setData(null);setError(e.message)}}finally{if(!signal.aborted)setLoading(false)}
 },[range])
 useEffect(()=>{const controller=new AbortController();setData(null);load(controller.signal);const timer=setInterval(()=>{if(!document.hidden)load(controller.signal)},60000);return()=>{controller.abort();clearInterval(timer)}},[load,refreshKey,refresh])
 return <section className="admin-card admin-traffic" aria-labelledby="traffic-heading"><div className="admin-card-heading"><div><h3 id="traffic-heading">Website traffic · Google Analytics</h3><p>Real reports from the connected GA4 property</p></div><button type="button" disabled={loading} onClick={()=>setRefresh(value=>value+1)}>{loading?'Refreshing…':'Refresh traffic'}</button></div>
  <div className="admin-traffic-ranges" role="group" aria-label="Traffic report period">{ranges.map(([id,label])=><button type="button" aria-pressed={range===id} key={id} onClick={()=>{setData(null);setRange(id)}}>{label}</button>)}</div>
  {error&&<p role="alert" className="portal-form-error">{error}</p>}
  {!data&&!error&&<p role="status">Loading Google reports…</p>}
  {data&&!data.configured&&<div className="admin-empty"><h4>GA4 reporting connection needed</h4><p>The website tag is installed. Reports need the numeric Property ID and a server-side reporting credential.</p><p>Property ID: {data.propertyConfigured?'Configured':'Missing'} · Read-only credential: {data.credentialsConfigured?'Configured':'Missing'}</p><p>In GA4 Admin, open Property details and use the numeric Property ID. Give the reporting service account Viewer access in Property access management. Enable the Google Analytics Data API and save its JSON key privately in hosting settings. The G- measurement ID cannot provide report access.</p></div>}
  {data?.connected&&<><div className="admin-traffic-metrics">{[['Active users · last 30 minutes',data.realtime?.activeUsers,'Entire connected GA4 property'],['Active users',data.history?.activeUsers,'Selected period · ascore.ae'],['Sessions',data.history?.sessions,'Selected period · ascore.ae'],['Page views',data.history?.pageViews,'Selected period · ascore.ae']].map(([label,value,note])=><div key={label}><span>{label}</span><strong>{count(value)}</strong><small>{note}</small></div>)}</div><p className="admin-footnote">Dates use {data.history.timeZone}. Reports can arrive later than Realtime. Realtime fetched {stamp(data.realtime.fetchedAt)}; traffic fetched {stamp(data.history.fetchedAt)}. Refreshes every minute while this page is visible.</p><h4>Traffic sources · Top 10 by sessions</h4>{data.history.sources.length?<div className="workspace-table-wrap"><table className="workspace-table"><thead><tr><th>Source</th><th>Medium</th><th>Sessions</th></tr></thead><tbody>{data.history.sources.map((row,i)=><tr key={i}><td>{row.source||'(not set)'}</td><td>{row.medium||'(not set)'}</td><td>{count(row.sessions)}</td></tr>)}</tbody></table></div>:<p>No source rows returned for this period.</p>}{data.history.thresholded&&<p className="admin-footnote">Google applied privacy thresholding; this report may omit data.</p>}{data.history.otherRow&&<p className="admin-footnote">Google grouped additional source rows under (other).</p>}<p className="admin-footnote">These are Google’s recorded sources. The current consent-controlled tag omits campaign queries and referrers, which limits attribution. Visitors who decline measurement are not measured by this tag.</p></>}
 </section>
}
