import { useState } from 'react'
import { portalRequest } from '../../services/portalApi'
const types=[['crmLead','CRM lead'],['crmContact','CRM contact'],['booksCustomer','Books customer'],['booksVendor','Books vendor'],['quotation','Books quotation'],['invoice','Books invoice'],['bill','Books bill']]
export default function ZohoConnections({data,onRefresh}) {
  const [resource,setResource]=useState('crmLead'),[localId,setLocalId]=useState(''),[preview,setPreview]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const records=resource==='crmLead'?data.leads:['crmContact','booksCustomer','booksVendor'].includes(resource)?data.clients:data.documents.filter(d=>d.kind===resource)
  const selected=records.some(item=>item.id===localId)?localId:''
  const act=async(action,body)=>{setError('');setNotice('');setBusy(true);try{const result=await portalRequest(`/integrations/zoho/${action}`,{method:'POST',body});await onRefresh();return result}catch(err){setError(err.message)}finally{setBusy(false)}}
  const selectResource=value=>{setResource(value);setLocalId('');setPreview(null)}
  return <><div className="workspace-form-grid">{[['crm','Zoho CRM','Leads and client contacts'],['books','Zoho Books','Customers, vendors, quotations, invoices and bills']].map(([key,title,description])=><section className="workspace-panel" key={key}><p className="workspace-connection-status">{data.integrations?.[key]?.connected?'SERVER CONNECTION VERIFIED':data.integrations?.[key]?.configured?'SERVER CONFIGURED · VERIFICATION PENDING':'NOT CONNECTED TO THIS WEBSITE'}</p><h2>{title}</h2><p>{description}</p><p>This website uses separately approved server access. Assistant account access does not connect this portal.</p><button disabled={busy||!data.integrations?.[key]?.configured} onClick={async()=>{if(await act('verify',{service:key}))setNotice(`${title} server access verified.`)}}>Verify server connection</button></section>)}</div>
    <section className="workspace-panel"><h2>Review one record for sync</h2><p>Link existing records by their verified Zoho ID to prevent duplicates. Review the exact outgoing data before confirming a write. Project progress stays in this portal; financial balances are tracked locally until reconciliation is configured.</p>
      <div className="workspace-fields-grid"><label>Record type<select value={resource} onChange={e=>selectResource(e.target.value)}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Local record<select value={selected} onChange={e=>{setLocalId(e.target.value);setPreview(null)}}><option value="">Select record</option>{records.map(item=><option key={item.id} value={item.id}>{item.name||item.invoiceNumber||item.title}</option>)}</select></label></div>
      <form className="workspace-fields-grid" onSubmit={async e=>{e.preventDefault();const externalId=new FormData(e.currentTarget).get('externalId');if(await act('link',{localId:selected,resource,externalId})){setPreview(null);setNotice('Existing Zoho record verified and linked.')}}}><label>Existing Zoho record ID<input name="externalId" pattern="[0-9]{5,30}" required maxLength={30}/></label><button disabled={busy||!selected}>Verify and link existing record</button></form>
      <button disabled={busy||!selected} onClick={async()=>{const result=await act('preview',{localId:selected,resource});if(result)setPreview(result)}}>Preview sync draft</button>
      {preview&&<div className="workspace-sync-preview"><p>{preview.method==='POST'?'Create a new record':'Update the linked record'} · {preview.service.toUpperCase()} · {preview.state}</p><pre>{JSON.stringify(preview.payload,null,2)}</pre><p>{data.integrations?.writesEnabled?'Confirming will write this reviewed record to Zoho. It will not send an invoice, charge a customer or record a payment.':'Live writes are disabled. An operator must separately approve server credentials and enable the sync setting.'}</p><button disabled={busy||!data.integrations?.writesEnabled||preview.state!=='ready'} onClick={async()=>{if(await act('sync',{localId:preview.localId,resource:preview.resource,confirmDigest:preview.digest})){setPreview(null);setNotice('Reviewed record synced successfully.')}}}>Confirm reviewed record sync</button></div>}
      {error&&<p role="alert" className="portal-form-error">{error}</p>}{notice&&<p role="status" className="portal-notice">{notice}</p>}
      <h3>Books balance reconciliation</h3><p>Refresh up to 25 linked records. Remote balances are displayed separately from manual local settlements.</p><button disabled={busy||!data.integrations?.books?.connected} onClick={async()=>{const result=await act('pull-balances',{});if(result)setNotice(`${result.refreshed} linked Books records refreshed.`)}}>Refresh linked Books balances</button><h3>Verified record links</h3><ul>{data.integrations?.links?.map(item=><li key={`${item.localId}-${item.resource}`}>{types.find(([id])=>id===item.resource)?.[1]} · {item.localId} → {item.externalId}</li>)}</ul>
    </section></>
}
