import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {runInNewContext} from 'node:vm'
const source=readFileSync(new URL('../scripts/google/ascore-friday-sessions.gs',import.meta.url),'utf8')
function script({local='Fri 09',valid=true,mailFails=false,completeFails=false,sender='ascorecreative@gmail.com'}={}){
 const actions=[],mails=[],triggers=[],logs=[];let claimed=false
 const sandbox={console:{log:v=>logs.push(v)},PropertiesService:{getScriptProperties:()=>({getProperty:()=> 'd'.repeat(64)})},Session:{getEffectiveUser:()=>({getEmail:()=>sender})},Utilities:{formatDate:()=>local},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock:()=>{}})},MailApp:{getRemainingDailyQuota:()=>100,sendEmail:m=>{mails.push(m);if(mailFails)throw Error('Ambiguous')}},ScriptApp:{getProjectTriggers:()=>triggers,newTrigger:name=>({timeBased:()=>({everyMinutes:n=>({create:()=>triggers.push({getHandlerFunction:()=>name,interval:n})})})})},UrlFetchApp:{fetch:(_url,options)=>{const p=JSON.parse(options.payload);actions.push(p.action);if(p.action==='complete'&&completeFails)throw Error('Offline');let result={ready:true,emailTime:'Friday 09:00 Asia/Dubai',meetingTime:'Friday 14:00 Asia/Dubai'};if(p.action==='claim'){result={claim:claimed?null:{week:'2026-10-09',recipient:'a'.repeat(64),token:'b'.repeat(64),to:'buyer@example.com',subject:'Friday live session',text:'Join https://meet.google.com/abc-defg-hij'}};claimed=true}if(p.action==='validate')result={valid};return{getResponseCode:()=>200,getContentText:()=>JSON.stringify(result)}}}}
 runInNewContext(source,sandbox);return {sandbox,actions,mails,triggers,logs}
}
test('Google setup verifies without sending mail and installs only one minute trigger',()=>{const s=script();s.sandbox.verifyAscoreSetup();s.sandbox.installAscoreSchedule();s.sandbox.installAscoreSchedule();assert.equal(s.mails.length,0);assert.equal(s.triggers.length,1);assert.equal(s.triggers[0].interval,1)})
test('Google script sends from verified Ascore account only during Friday window',()=>{for(const local of ['Thu 09','Fri 08','Fri 14']){const s=script({local});s.sandbox.sendFridaySessions();assert.equal(s.actions.length,0)}const s=script();s.sandbox.sendFridaySessions();assert.equal(s.mails.length,1);assert.equal(s.mails[0].name,'Ascore Creative');assert.equal(s.mails[0].replyTo,'ascorecreative@gmail.com');const wrong=script({sender:'accurweb@gmail.com'});assert.throws(()=>wrong.sandbox.sendFridaySessions(),/Ascore Creative account/);assert.equal(wrong.mails.length,0)})
test('invalid/refunded claims are skipped and ambiguous sends are never resent',()=>{const skipped=script({valid:false});skipped.sandbox.sendFridaySessions();assert.equal(skipped.mails.length,0);assert.ok(skipped.actions.includes('complete'));const uncertain=script({mailFails:true});uncertain.sandbox.sendFridaySessions();uncertain.sandbox.sendFridaySessions();assert.equal(uncertain.mails.length,1);const lostAck=script({completeFails:true});assert.throws(()=>lostAck.sandbox.sendFridaySessions(),/Offline/);lostAck.sandbox.sendFridaySessions();assert.equal(lostAck.mails.length,1)})
