import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowUpRight, Menu, X, Monitor, PenTool, Box, Workflow, BriefcaseBusiness } from 'lucide-react'
import IdeaHero from './IdeaHero'
import OriginalVideoHero from './OriginalVideoHero'
import ServiceDetailsDialog from './ServiceDetailsDialog'
import AfterVideoWhatsApp from './AfterVideoWhatsApp'
import ContactEnquiryForm from './ContactEnquiryForm'
import AscoreDigitalProducts from './products/AscoreDigitalProducts'
import { selectedWork, services } from '../../lib/siteContent'
import { publicRoutes, servicePages } from '../../lib/siteRoutes'
import '../../styles/site.css'
import '../../styles/reference-sections.css'

function useReducedMotion() {
 const [reduced,setReduced]=useState(false)
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(query.matches||new URLSearchParams(window.location.search).get('motion')==='reduce');sync();query.addEventListener('change',sync);return()=>query.removeEventListener('change',sync)},[])
 return reduced
}
// One shared passive scroll clock. Subscribers only measure sections near the viewport.
const subscribers=new Set();let scrollFrame=0
function dispatchScroll(){scrollFrame=0;subscribers.forEach(fn=>fn())}
function scheduleScroll(){if(!scrollFrame)scrollFrame=requestAnimationFrame(dispatchScroll)}
function useSectionProgress(ref,reduced,callback){
 useEffect(()=>{if(reduced){callback(1);return}const update=()=>{const element=ref.current;if(!element)return;const box=element.getBoundingClientRect();if(box.bottom<0||box.top>window.innerHeight)return;callback(Math.max(0,Math.min(1,(window.innerHeight-box.top)/(box.height+window.innerHeight))))};if(!subscribers.size){window.addEventListener('scroll',scheduleScroll,{passive:true});window.addEventListener('resize',scheduleScroll)}subscribers.add(update);update();return()=>{subscribers.delete(update);if(!subscribers.size){window.removeEventListener('scroll',scheduleScroll);window.removeEventListener('resize',scheduleScroll);cancelAnimationFrame(scrollFrame);scrollFrame=0}}},[ref,reduced,callback])
}
function BrandArtwork({header=false}) {return <span className="brand-logo" aria-hidden="true"><img className="brand-colour" src="/ascore-logo-official.png" width="783" height="330" alt="" loading={header?undefined:'lazy'}/><span className={`brand-wordmark-art ${header?'header-wordmark':'footer-wordmark'}`} style={{maskImage:"url('/ascore-logo-official.png')",WebkitMaskImage:"url('/ascore-logo-official.png')"}}/></span>}
function SiteHeader(){
 const [open,setOpen]=useState(false),[dark,setDark]=useState(true);const button=useRef(null),nav=useRef(null)
 useEffect(()=>{
  if(!open)return
  const compact=window.matchMedia('(max-width:1024px)')
  const reset=()=>{if(!compact.matches)setOpen(false)}
  const key=event=>{
   if(event.key==='Escape'){event.preventDefault();setOpen(false);button.current?.focus()}
   if(event.key==='Tab'){
    const items=[button.current,...nav.current.querySelectorAll('a')].filter(Boolean)
    const index=items.indexOf(document.activeElement)
    event.preventDefault()
    items[(index+(event.shiftKey?-1:1)+items.length)%items.length]?.focus()
   }
  }
  reset();document.body.classList.add('site-menu-open')
  window.addEventListener('keydown',key);compact.addEventListener('change',reset)
  return()=>{window.removeEventListener('keydown',key);compact.removeEventListener('change',reset);document.body.classList.remove('site-menu-open')}
 },[open])
 useEffect(()=>{let frame=0;const sync=()=>{frame=0;const section=document.elementsFromPoint(window.innerWidth/2,35).find(element=>!element.closest('.site-header')&&element.closest('[data-theme]'))?.closest('[data-theme]');if(section)setDark(section.dataset.theme==='dark')};const schedule=()=>{if(!frame)frame=requestAnimationFrame(sync)};const observer=new MutationObserver(schedule);observer.observe(document.querySelector('main'),{attributes:true,attributeFilter:['data-theme'],subtree:true});sync();window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);return()=>{observer.disconnect();window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);cancelAnimationFrame(frame)}},[])
 return <header className={`site-header reference-header${dark?' is-dark':' is-light'}${open?' menu-is-open':''}`}><span className="header-blur" aria-hidden="true" style={{backdropFilter:'blur(18px)',WebkitBackdropFilter:'blur(18px)'}}/><a className="brand-lockup" href="/" aria-label="Ascore Creative home"><BrandArtwork header/></a><nav ref={nav} className={`site-nav${open?' is-open':''}`} id="main-navigation" aria-label="Main navigation">{[['Home','/'],['Work','/work/'],['Services','/services/'],['About','/about/'],['Contact','/contact/'],['Client portal','/portal/']].map(([label,url])=><a key={url} href={url} onClick={()=>setOpen(false)}>{label}</a>)}</nav><a className="header-cta" href="/contact/">Get in touch <ArrowUpRight size={16}/></a><button ref={button} className="menu-toggle" type="button" aria-expanded={open} aria-controls="main-navigation" aria-label={open?'Close menu':'Open menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
}
function Manifesto({reduced}){
 const ref=useRef(null),write=useRef(p=>ref.current?.style.setProperty('--read',p));useSectionProgress(ref,reduced,write.current)
 const words='We turn ambitious ideas into digital experiences people remember.'.split(' ')
 return <section ref={ref} className="manifesto section-pad" id="about" data-theme="light"><div className="section-meta"><span>01 / The studio</span><span>UAE / India / Worldwide</span></div><div className="manifesto-grid"><h2>{words.map((word,i)=><span key={i} className={i===5||i===6?'accent-word':''} style={{'--word':i}}>{word} </span>)}</h2><aside><p>Ascore Creative brings strategy, design and engineering together for brands ready to do more than blend in.</p><a className="text-link" href="/about/">Meet the studio <ArrowUpRight size={18}/></a><a className="text-link" href="/services/">Explore our services <ArrowUpRight size={18}/></a></aside></div></section>
}
function Statement({reduced}){
 const ref=useRef(null);const [index,setIndex]=useState(0);const words=['possibility.','perspective.','dimension.']
 useEffect(()=>{if(reduced)return;let timer;const observer=new IntersectionObserver(([entry])=>{clearInterval(timer);if(entry.isIntersecting)timer=setInterval(()=>setIndex(i=>(i+1)%3),2400)});observer.observe(ref.current);return()=>{observer.disconnect();clearInterval(timer)}},[reduced])
 return <section ref={ref} className="statement section-pad" data-theme="light"><p>MAKE SPACE FOR WHAT COMES NEXT</p><h2>Make space for<br/><em>{reduced?'possibility.':words[index]}</em></h2><span className="statement-note">Different disciplines. One connected perspective.</span></section>
}
function PracticeBand(){return <section className="practice-band" data-theme="dark" aria-label="Our disciplines">{['STRATEGY','DESIGN','ENGINEERING','AUTOMATION'].map(word=><span key={word}>{word}</span>)}</section>}
function Services({onOpen}){const icons=[Monitor,PenTool,Box,Workflow,BriefcaseBusiness];return <section className="stacked-services section-pad" id="services" data-theme="dark"><div className="section-meta"><span>02 / What we do</span><span>One connected practice</span></div><div className="services-intro"><h2>Every detail.<br/><em>Considered.</em></h2><p>From the first thought to the final interaction, we bring the right disciplines together to make ideas real.</p></div><div className="service-stack">{services.map(([number,title,text],i)=><article className="service-stack-card" key={number} style={{'--card':i}}><span className="service-number">{number} / ASCORE SERVICES</span><h3><button className="service-detail-trigger" type="button" aria-haspopup="dialog" onClick={event=>onOpen(i,event.currentTarget)}>{title}</button></h3><p>{text}</p><a className="text-link" href={servicePages[i].path}>Explore {title.toLowerCase()} <ArrowUpRight size={20}/></a><span className="service-card-glyph" aria-hidden="true">{(() => {const Icon=icons[i];return <Icon strokeWidth={1.1}/>})()}</span></article>)}</div></section>}
function WorkArt({item}){return <div className={`work-art work-art-${item.tone} live-work-preview`}><div className="project-browser" aria-hidden="true"><div className="project-browser-bar"><i/><i/><i/></div><img src={`/work/${item.slug}-desktop.webp`} alt="" width="1440" height="920" loading="lazy" decoding="async"/></div><div className="project-phone" aria-hidden="true"><img src={`/work/${item.slug}-mobile.webp`} alt="" width="388" height="643" loading="lazy" decoding="async"/></div><span className="project-capture-label">DESKTOP + MOBILE / LIVE SITE</span></div>}

function Work({radial=false,reduced=false}){
 const ref=useRef(null),write=useRef(()=>{});write.current=()=>{const el=ref.current;if(!el)return;const box=el.getBoundingClientRect(),p=Math.max(0,Math.min(1,-box.top/Math.max(1,box.height-window.innerHeight)));el.style.setProperty('--deck',p)};const stable=useRef(p=>write.current(p));useSectionProgress(ref,reduced,stable.current)
 return <section ref={ref} className={radial&&!reduced?'radial-work':'work-section section-pad'} id="work" data-theme="dark" style={{'--deck-turn':`${(selectedWork.length-1)*24}deg`}}><div className={radial&&!reduced?'radial-stage':''}><div className="work-heading"><h2>Always another<br/><em>perspective.</em></h2><p>Real desktop and mobile views of selected websites. Explore each live experience.</p></div><div className={radial&&!reduced?'radial-wheel':'work-grid'}>{selectedWork.map((item,i)=><a className={`work-card ${item.tone}`} style={{'--slot':i}} key={item.name} href={item.url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ${item.name}, opens in a new tab`}><div className="work-image"><WorkArt item={item} index={i}/></div><div className="work-card-meta"><span>{item.type}</span><ArrowUpRight size={17}/></div><h3>{item.name}</h3></a>)}</div>{radial&&!reduced&&<nav className="radial-links" aria-label="Selected websites">{selectedWork.map(item=><a key={item.name} href={item.url} target="_blank" rel="noopener noreferrer">{item.name} <ArrowUpRight size={13}/></a>)}</nav>}</div></section>
}
function Process(){return <section className="process-section section-pad" id="process" data-theme="light"><div className="section-meta"><span>How we work</span><span>Clarity at every step</span></div><div className="process-main"><div><p className="eyebrow">A BETTER WAY TO BUILD</p><h2>Curiosity first.<br/><em>Craft always.</em></h2></div><p>We ask better questions, find the sharpest idea, then shape it with care.</p></div><div className="process-steps">{[['Discover','Find the signal.','Understand the audience, ambition and opportunity.'],['Design','Give it form.','Build a distinct visual and interaction language.'],['Deliver','Make it matter.','Engineer, refine and prepare the agreed handover.']].map(([label,title,text],i)=><div key={label}><span>0{i+1} / {label}</span><h3>{title}</h3><p>{text}</p></div>)}</div></section>}
function Contact(){return <section className="contact-section section-pad" id="contact" data-theme="dark"><div className="section-meta"><span>Next chapter</span><span>Ajman-based · Serving the UAE and beyond</span></div><p className="contact-lead">Have something<br/>in mind?</p><a className="contact-big" href="mailto:info@ascore.ae?subject=Project%20enquiry">Let’s make it<br/><em>remarkable.</em><ArrowUpRight aria-hidden="true"/></a><ContactEnquiryForm/><div className="contact-ways"><a href="mailto:info@ascore.ae">info@ascore.ae <ArrowUpRight size={17}/></a><a href="https://wa.me/971568555626" target="_blank" rel="noopener noreferrer">WhatsApp <ArrowUpRight size={17}/></a><a href="tel:+971543878726">+971 54 387 8726 <ArrowUpRight size={17}/></a></div></section>}
function Footer(){
 const ref=useRef(null),[visible,setVisible]=useState(false)
 useEffect(()=>{let inView=false;const sync=()=>setVisible(inView&&!document.hidden);const observer=new IntersectionObserver(([entry])=>{inView=entry.isIntersecting;sync()},{threshold:.05});observer.observe(ref.current);document.addEventListener('visibilitychange',sync);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',sync)}},[])
 return <footer ref={ref} className={`site-footer${visible?' is-in-view':''}`} data-theme="dark"><div className="footer-top"><a className="brand-lockup" href="/" aria-label="Ascore Creative home"><BrandArtwork/></a><p>Ideas with dimension.<br/>Ajman, United Arab Emirates.</p></div><nav className="service-footer" aria-label="Service navigation">{servicePages.map(page=><a key={page.id} href={page.path}>{page.name} <ArrowUpRight size={14}/></a>)}</nav><div className="footer-bottom"><span>© {new Date().getFullYear()} ASCORE CREATIVE FZC LLC</span><nav aria-label="Footer navigation">{publicRoutes.filter(page=>!page.service).map(page=><a href={page.path} key={page.id}>{page.label}</a>)}<a href="/portal/">Client portal</a></nav></div></footer>}
function PageHeading({page}){return <section className="public-page-heading section-pad" data-theme="light"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span>{page.service&&<><a href="/services/">Services</a><span>/</span></>}<span aria-current="page">{page.label}</span></nav><p className="eyebrow">ASCORE CREATIVE / {page.service?'SERVICES':'THE STUDIO'}</p><h1>{page.label}</h1><p className="page-lead">{page.lead||{services:'Five disciplines. One connected creative and digital practice.',work:'A selection of websites, captured on desktop and mobile.',about:'Independent thinking. Connected craft. Ideas with dimension.',contact:'Let’s find the shape of your next idea.'}[page.id]}</p></section>}
function ServiceDetail({page}){return <><section className="service-detail section-pad" data-theme="light"><p className="detail-intro">{page.intro}</p><div className="detail-grid"><h2>What we can shape together</h2><ul>{page.deliverables.map(text=><li key={text}>{text}</li>)}</ul></div><div className="detail-grid"><h2>A clear path through the work</h2><ol>{page.process.map(([title,text])=><li key={title}><h3>{title}</h3><p>{text}</p></li>)}</ol></div><p className="scope-note">Deliverables, timelines and specialist involvement depend on the agreed engagement. Start with a conversation about your project.</p><a className="text-link" href="/contact/">Discuss {page.name.toLowerCase()} <ArrowUpRight size={18}/></a></section><PracticeBand/><Contact/></>}
export default function PublicSite({page=publicRoutes[0]}){
 const reduced=useReducedMotion();const home=page?.id==='home'
 const [selectedService,setSelectedService]=useState(null)
 const openService=useCallback((index,opener)=>setSelectedService({page:servicePages[index],opener}),[])
 const closeService=useCallback(()=>setSelectedService(null),[])
 return <div className={`new-site${reduced?' motion-reduced':''}${home?'':' inner-page'}`}><a className="skip-link" href="#main-content">Skip to content</a><SiteHeader/><main id="main-content">{home?<><IdeaHero reducedMotion={reduced} onOpenService={openService}/>{reduced&&<OriginalVideoHero reducedMotion standalone/>}<AscoreDigitalProducts/><Manifesto reduced={reduced}/><Statement reduced={reduced}/><PracticeBand/><Services onOpen={openService}/><Work radial reduced={reduced}/><Process/><Contact/></>:page?<><PageHeading page={page}/>{page.service?<ServiceDetail page={page}/>:page.id==='services'?<><Services onOpen={openService}/><Contact/></>:page.id==='work'?<><Work reduced={reduced}/><Contact/></>:page.id==='about'?<><section className="service-detail section-pad" data-theme="light"><p className="detail-intro">Ascore Creative is an Ajman-based creative and digital studio serving Dubai, the wider UAE and global projects. We bring strategy, design and engineering into one connected practice.</p><div className="detail-grid"><h2>Ideas, given form.</h2><p>From brand identities and digital products to immersive experiences and operational workflows, we shape the agreed scope around the people who will use it.</p></div></section><Process/><PracticeBand/><Contact/></>:<Contact/>}</>:<section className="public-page-heading section-pad" data-theme="light"><h1>That page has moved out of frame.</h1><p className="page-lead">Explore our studio, services and selected work.</p><a className="text-link" href="/">Return home ↗</a></section>}</main><Footer/>{home&&<AfterVideoWhatsApp/>}{selectedService&&<ServiceDetailsDialog selection={selectedService} onClose={closeService}/>}</div>
}
